data limit filter
Pepperi-Addons/data-queries pull request #115
Opened 2024-03-25 13:38 UTC by leonPep42

2024-03-26 07:59 UTC, saargt requested changes

2024-03-26 07:59 UTC, saargt commented on client-side/src/assets/i18n/en.json
> +	"Preview_Description": "The queries are limited to {{number}} days. Please contact us If you wish to increase the period.",
Is this string approved by product?

2024-03-26 07:59 UTC, saargt commented on server-side/installation.ts
> +			await varSettingsService.setDefaultVarSettings();
VarSettingsService should instantiate\get an instance of UtilitiesService, and deploy\destroy whatever resources it needs.

2024-03-26 07:59 UTC, saargt commented on addon.config.json
> +  "AddonVersion": "1.4.9",
You need to add a dpeendency on KMS, right?
Talk to Lior, see if they have configured that in the addons-for-dependencies configuration field. If she doesn't know what you mean or how to do it, LMK.

2024-03-26 07:59 UTC, saargt commented on server-side/services/varSettings.service.ts
> +		const queries: DataQuery[] = await this.papiClient.get('/data_queries?fields=Key&page_size=-1');
You make an additional HTTP call here, running an extra Lambda.
Modify QueryService's constructor to recieve a PapiClient object, so you can instantiate it here.
Modify QueryService.find() to recieve a typed object query, than you can call it directly from this Lambda.

2024-03-26 07:59 UTC, saargt commented on server-side/services/varSettings.service.ts
> +		return await this.papiClient.post(`/addons/data/batch/${config.AddonUUID}/${DATA_QUREIES_TABLE_NAME}`, {Objects: queries});
How many data_queries are there? I see you pass page_size=-1 (which you know I'm not a fan of), and than use batch upsert, which I think is limited to 500.

2024-03-26 07:59 UTC, saargt commented on server-side/services/varSettings.service.ts
> +			TrialEndDate: new Date().toLocaleString()
I think it should be toIsoString(). toLocaleString() will return a string representing the local time where the Lambda is run, which isn't intuitive.

2024-03-26 07:59 UTC, saargt commented on server-side/services/varSettings.service.ts
> +		await this.papiClient.post(`/addons/api/8b4a1bd8-a2eb-4241-85ac-89c9e724e900/api/addon_data?addon_uuid=${config.AddonUUID}&key=${key}`, {
Guessing the KMS doesn't have multiple upsert endpoint?

2024-03-26 07:59 UTC, saargt commented on server-side/services/elastic.service.ts
> +	if (query.VarSettings.License === 'Free version' && query.VarSettings.TrialEndDate < new Date().toLocaleString()) {
License whould be a closed list of string options (Something like License = 'Free Version' | 'Full Version'...), to avoid typos, having to update multuiple locations in the code if it is ever changed, etc.

2024-03-26 07:59 UTC, saargt commented on server-side/installation.ts
> +		if (request.body.FromVersion && semver.compare(request.body.FromVersion, '1.4.9') < 0)
This should also be done on install

2024-03-26 09:26 UTC, leonPep42 commented on client-side/src/assets/i18n/en.json
> +	"Preview_Description": "The queries are limited to {{number}} days. Please contact us If you wish to increase the period.",
Eyal always defines his strings ✅

2024-03-27 10:27 UTC, leonPep42 commented on server-side/services/varSettings.service.ts
> +		return await this.papiClient.post(`/addons/data/batch/${config.AddonUUID}/${DATA_QUREIES_TABLE_NAME}`, {Objects: queries});
Eyal said that hard limit is 150 queries

2024-03-27 10:29 UTC, leonPep42 commented on server-side/installation.ts
> +			await varSettingsService.setDefaultVarSettings();
I'm missing something. upsertRelation is async, so how can I call it from VarSettingsService constructor?

2024-03-27 10:43 UTC, leonPep42 commented on server-side/services/varSettings.service.ts
> +		await this.papiClient.post(`/addons/api/8b4a1bd8-a2eb-4241-85ac-89c9e724e900/api/addon_data?addon_uuid=${config.AddonUUID}&key=${key}`, {
right

2024-03-27 13:10 UTC, saargt approved these changes

2024-03-27 13:20 UTC, merged