fixed preview-description issue
Pepperi-Addons/data-queries pull request #122
Opened 2024-05-26 14:15 UTC by leonPep42

2024-05-26 14:20 UTC, saargt requested changes

2024-05-26 14:20 UTC, saargt commented on client-side/src/app/query-form/query-form.component.ts
> +		return (query.Limitations?.License === "Free version" && query.Limitations?.TrialEndDate < new Date().toLocaleString())
That's not how you compare date time in JS:
https://www.freecodecamp.org/news/javascript-date-comparison-how-to-compare-dates-in-js/

2024-05-26 14:51 UTC, leonPep42 commented on client-side/src/app/query-form/query-form.component.ts
> +		return (query.Limitations?.License === "Free version" && query.Limitations?.TrialEndDate < new Date().toLocaleString())
you mean I should use getTime?
we don't really need milliseconds comparison

2024-05-27 06:40 UTC, saargt requested changes

2024-05-27 06:40 UTC, saargt commented on client-side/src/app/query-form/query-form.component.ts
> +import { licenseOptions } from 'src/metadata/license';
Don't use absolute path, rather '../../metadata' or whatever.

2024-05-27 06:40 UTC, saargt commented on client-side/src/app/query-form/query-form.component.ts
> +		return (query.Limitations?.License === licenseOptions.Free && query.Limitations?.TrialEndDate?.getTime() < new Date().getTime())
query.Limitations?.TrialEndDate will be a string, not a Date object you can .getTime() on.

2024-05-27 06:47 UTC, leonPep42 commented on client-side/src/app/query-form/query-form.component.ts
> +import { licenseOptions } from 'src/metadata/license';
first I did this and vs code yelled on me, fixed now :/

2024-05-27 07:41 UTC, merged